<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SACHINN" ignored="0" name="BankingApp Test in IE" tests="2" failures="1" timestamp="18 Feb 2020 09:55:26 GMT" time="39.848" errors="0">
  <testcase name="loginFinance" time="36.482" classname="com.inetbanking.testCases.FivenanceLogin"/>
  <testcase name="loginFinance" time="36.488" classname="com.inetbanking.testCases.FivenanceLogin">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.aventstack.extentreports.ExtentObservable.lambda$saveTest$0(ExtentObservable.java:209)
at com.aventstack.extentreports.ExtentObservable$$Lambda$343/2078919047.accept(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.aventstack.extentreports.ExtentObservable.saveTest(ExtentObservable.java:209)
at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:234)
at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:247)
at com.inetbanking.utilities.Reporting.onTestSuccess(Reporting.java:51)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- loginFinance -->
</testsuite> <!-- BankingApp Test in IE -->
